export const data=[
    'all',
    'uefa champions league',
    'sales',
    'computers',
    'gaming',
    'african music',
    'Reactjs',
    'angular js',
    'react native',
    'use of api',
    'porn',
    'redux',
    'music',
    'algorithm art',
    'guitar',
    'bangali song',
    'coding',
    'cricket',
    'football',
    'real madrid',
    'gatsby',
    'poor coder',
    'drums',
    'action',
    'university',
    'advertisement',
    'davido',
    'wizkid',
    'don jazzy',
    'nicky minaj',
    'messi',
    'ronaldo',
    'fantasy',
    'adventure',
    'cartoons',
    'horror',
    'animal',
    'marvel',
    'hulk',
    'wwe',
    'spiderman',
    'superman',
    'batman',
    'nollywood',
    'bollywood',
    'yoruba',
    ]